export enum ACTIVE_TYPE {
    ADD_USERS = 'ADD-USERS',
    ADD_USER = 'ADD-USER',
    EDIT = 'EDIT',
    UN_EDIT = 'UN-EDIT',
    SET_NAME = 'SET-NAME',
    SET_SURNAME = 'SET-SURNAME',
    SET_PHONE = 'SET-PHONE',
}

export enum NEW_USER_TYPE {
    SET_NAME_VALUE = 'SET-NAME-VALUE',
    SET_SURNAME_VALUE = 'SET-SURNAME-VALUE',
    SET_PHONE_VALUE = 'SET-PHONE-VALUE',
    CLEAR = 'CLEAR',
}
